version: "3.5"

services:

  postgres:
    image: postgres:$POSTGRES_TAG
    container_name: "${PROJECT_NAME}_postgres"
    build: 
      dockerfile: Dockerfile
      context: ./services/postgres
      args:
        POSTGRES_TAG: $POSTGRES_TAG
    stop_grace_period: 60s
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - ${DB_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - /var/lib/postgresql/data
      - ./data:/var/data

  adminer:
    image: adminer:$ADMINER_TAG
    container_name: "${PROJECT_NAME}_adminer"
    stop_grace_period: 60s
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  node:
    image: "node:${NODE_TAG}"
    container_name: "${PROJECT_NAME}_node"
    stop_grace_period: 60s
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./server
      args:
        NODE_TAG: $NODE_TAG
    volumes:
      - ./server:/app
    environment:
      NODE_ENV: $NODE_ENV
      HOST: "0.0.0.0"
      Port: 3000
      NODE_API_SECRET: $NODE_API_SECRET
      DB_HOST: $DB_HOST
      DB_PORT: $DB_CONTAINER_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      NODE_DB_CLIENT: $NODE_DB_CLIENT
      NODE_RATE_LIMIT_REQUESTS: $NODE_RATE_LIMIT_REQUESTS
      NODE_RATE_LIMIT_RESET: $NODE_RATE_LIMIT_RESET
      NODE_CACHE_BACKEND: $NODE_CACHE_BACKEND
      NODE_CACHE_LIFETIME: $NODE_CACHE_LIFETIME
      NODE_REDIS_HOST: $NODE_REDIS_HOST
      NODE_REDIS_PORT: $NODE_REDIS_PORT
      NODE_ELASTICSEARCH_HOST: $NODE_ELASTICSEARCH_HOST
      NODE_ELASTICSEARCH_INDEX: $NODE_ELASTICSEARCH_INDEX
    ports:
      - "${NODE_PORT}:3000"
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_node=Host(`node.${PROJECT_BASE_URL}`)"
  
  nginx:
    image: nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    restart: always
    depends_on:
      - node
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./server:/var/www/html
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx=Host(`nginx.${PROJECT_BASE_URL}`)"

  redis:
    image: redis:$REDIS_TAG
    container_name: "${PROJECT_NAME}_redis"
    stop_grace_period: 60s
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_TAG
    container_name: "${PROJECT_NAME}_elasticsearch"
    stop_grace_period: 60s
    # restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_REST_PORT}:9200
      - ${ELASTICSEARCH_NODE_PORT}:9300
    environment:
      - $ES_JAVA_OPTS
      - $DISCOVERY_TYPE
      - $BOOTSTRAP_MEMORY_LOCK
      - $ELASTICSEARCH_CLUSTER_NAME
      #- $ELASTICSEARCH_NODE_NAME_MASTER
      #- $ELASTICSEARCH_CLUSTER_INITIAL_MASTER_NODES

networks:
  default:
      name: linux_package_search
